# Generated by Django 5.1.2 on 2024-10-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
